### ISSUE TITLE
`DescriptorBlindingKey` variants rustdoc

### ISSUE THREAD

**Issue by ok300** [Blockstream/lwk#7]
Please add a short rustdoc for `DescriptorBlindingKey` that mentions the differences and tradeoffs between the variants.

https://github.com/Blockstream/lwk/blob/03ed9e62eb69cfc37903d08e5998fa3ebffb2d2a/lwk_common/src/descriptor.rs#L126-L130

**Comment by LeoComandini** [comment]
Hi @ok300 ,
Added documentation in cfe9341 .
If you need further clarifications or more documentation feel free to raise more issues, they are very much welcome.

At this stage we left some documentation and polishing behind due to the large scope of the project. 
If something is not clear to you, please let us know so we can improve on that side.

**Comment by ok300** [comment]
Thanks @LeoComandini , the docs you added are very useful!
